### ISSUE TITLE
Add "References" page

### ISSUE THREAD

**Issue by UJehle** [goat-community/p4b-website#193]
**Background**
During the retreat, there was the idea that we should add a "References" page to our website. Elias and I discussed this and think it is true! Very often, people ask us about references. So having them directly on the website would be of great added value. We already have a "GOAT References" page, but all the projects are missing. 

We thought the best would be to use the GOAT references page (https://plan4better.de/goat-references/) therefore, and when the user clicks on one tile, we will be forwarded to a subpage with further information about the project.

**Tasks**
- [x] Create a mockup for mobile (Ana)
- [ ] #205
- [x] Implementing the necessary code (Sina)
- [ ] Filling the content (Ulrike)

**Comment by UJehle** [comment]
One thing that I forgot during the call: it would be nice to also have some labels here (like we also have it in the "blog" section).
![grafik](https://user-images.githubusercontent.com/49870195/219412076-529f4a9b-d1d3-4d2e-bea8-59aa6dc43a57.png)

I would then also see the "reference" page on a higher level and not within the "GOAT" section. 
![grafik](https://user-images.githubusercontent.com/49870195/219412597-c3f80c24-f499-49d9-9049-46c62a992aa5.png)

**Comment by UJehle** [comment]
Hi @cinaaaa,
I just had a look at the current state. It already looks good! 
But some first things to improve:

1. could you add German translations for these keywords?
"Reference" = "Referenz"
"Planning Cases = "Bearbeitete Planungsfälle"
"Overview" = "Inhalt"
"Client" = "Auftraggeber"
"Period of time" = "Laufzeit"
"Contact person" = "Ansprechperson"
"Get GOAT for your city" = "Mehr zu GOAT erfahren" (could we make this button flexible in terms of text & URL? As we might want to link to different pages, depending on the reference)

2. Here, the layout is not in line: 
![grafik](https://user-images.githubusercontent.com/49870195/222817915-f1e0f7d2-c8d1-49ed-9d57-cba3ecf9953c.png)
As far as I understood, Ana had foreseen to have these two block in one line.

3. Where does this description come from? I think it was not part of the Mockup.
![grafik](https://user-images.githubusercontent.com/49870195/222819145-4572c0db-9837-4177-88ed-25c3af036e91.png)

4. Sometimes it somehow happens that the page looks like this:
![grafik](https://user-images.githubusercontent.com/49870195/222820749-1d195c0f-18ee-4ed8-ba8e-44c568b476dd.png)
Not sure what is the reason therefore.

**Comment by UJehle** [comment]
And one last question for today:
![grafik](https://user-images.githubusercontent.com/49870195/222834889-0a6b806f-b11f-4af7-a288-f490fa0621db.png)
Is it possible to influence the order of the references? It would be nice if we could define the order somewhere, like it was implemented for the "old" reference page

**Comment by UJehle** [comment]
Hi @cinaaaa, 
one additional thing which we discussed in the call, but did not document here: 
could you open the images in a pop-up when the user clicks on them? 
![grafik](https://user-images.githubusercontent.com/49870195/224554119-c56a9769-aba5-4361-9a9c-cffe71edb7f5.png)

**Comment by AnaSasso** [comment]
Corrections:
For more detail visit the[ Figma File](https://www.figma.com/file/SmmQgQZ9QvWwg62NBlJcN8/P4B-Website-local?node-id=71%3A365&t=UX70NyaQXQaXHg4p-1)

![Image](https://user-images.githubusercontent.com/116002158/225729819-cc7dd78f-9593-41d3-8e80-b63dafac1ac0.png)
![Image](https://user-images.githubusercontent.com/116002158/225729818-e0508b8f-5fae-44c0-a7a6-985b609eda86.png)

**Comment by UJehle** [comment]
For this project, we only have two images. Is it possible to align them in the center? 
![grafik](https://user-images.githubusercontent.com/49870195/225744013-9edc69fb-c4a5-4196-9a8b-6e849a0d037b.png)

**Comment by UJehle** [comment]
Furthermore, comments 3., 4. and 6. from above seem to be not fixed yet.

**Comment by AnaSasso** [comment]
Design Review
Review page padding= 200px

![Image](https://user-images.githubusercontent.com/116002158/225747195-8d97cdda-ed90-48e3-937a-c945887837ad.png)

**Comment by cinaaaa** [comment]
@UJehle Comment 3, the description can be deleted, I copied it from other pages and thought it was useful, and turns out that it is not, I'm still searching for a way also to sort reference page items and still working on it.

**Comment by AnaSasso** [comment]
Design Review:

> 1. Cards at reference list page: 
Change this card interactions, instead of the text underlined, increase its shadow 4%
> 
> <img src="https://user-images.githubusercontent.com/116002158/225954274-3113fc73-6b35-45d0-a20a-ba2988ad0032.png" width=30% height=30%>
> 

> 2. Cards bottom reference page: 
> Use the same card as the reference list, I believe these are different👇
> 
> <img src="https://user-images.githubusercontent.com/116002158/225955221-9569b8e0-c990-46d1-9bdd-d28267e3e7e6.png" width=50% height=50%>
> 
>
